//
// Generated file, do not edit! Created by opp_msgtool 6.2 from messages/ARPPacket.msg.
//

#ifndef __ARPPACKET_M_H
#define __ARPPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ARPPacket;
/**
 * Class generated from <tt>messages/ARPPacket.msg:1</tt> by opp_msgtool.
 * <pre>
 * message ARPPacket
 * {
 *     string srcIP;
 *     string dstIP;
 *     string srcMAC;
 *     string dstMAC;
 *     bool isRequest; // true = request, false = reply
 * }
 * </pre>
 */
class ARPPacket : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string srcIP;
    omnetpp::opp_string dstIP;
    omnetpp::opp_string srcMAC;
    omnetpp::opp_string dstMAC;
    bool isRequest_ = false;

  private:
    void copy(const ARPPacket& other);

  protected:
    bool operator==(const ARPPacket&) = delete;

  public:
    ARPPacket(const char *name=nullptr, short kind=0);
    ARPPacket(const ARPPacket& other);
    virtual ~ARPPacket();
    ARPPacket& operator=(const ARPPacket& other);
    virtual ARPPacket *dup() const override {return new ARPPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSrcIP() const;
    virtual void setSrcIP(const char * srcIP);

    virtual const char * getDstIP() const;
    virtual void setDstIP(const char * dstIP);

    virtual const char * getSrcMAC() const;
    virtual void setSrcMAC(const char * srcMAC);

    virtual const char * getDstMAC() const;
    virtual void setDstMAC(const char * dstMAC);

    virtual bool isRequest() const;
    virtual void setIsRequest(bool isRequest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ARPPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ARPPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ARPPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<ARPPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ARPPACKET_M_H

