//
// Generated file, do not edit! Created by opp_msgtool 6.2 from messages/DNSPacket.msg.
//

#ifndef __DNSPACKET_M_H
#define __DNSPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DNSPacket;
/**
 * Class generated from <tt>messages/DNSPacket.msg:1</tt> by opp_msgtool.
 * <pre>
 * message DNSPacket
 * {
 *     string queryName;
 *     string answerIP;
 *     bool isQuery; // true = query, false = response
 * }
 * </pre>
 */
class DNSPacket : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string queryName;
    omnetpp::opp_string answerIP;
    bool isQuery_ = false;

  private:
    void copy(const DNSPacket& other);

  protected:
    bool operator==(const DNSPacket&) = delete;

  public:
    DNSPacket(const char *name=nullptr, short kind=0);
    DNSPacket(const DNSPacket& other);
    virtual ~DNSPacket();
    DNSPacket& operator=(const DNSPacket& other);
    virtual DNSPacket *dup() const override {return new DNSPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getQueryName() const;
    virtual void setQueryName(const char * queryName);

    virtual const char * getAnswerIP() const;
    virtual void setAnswerIP(const char * answerIP);

    virtual bool isQuery() const;
    virtual void setIsQuery(bool isQuery);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DNSPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DNSPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DNSPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<DNSPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DNSPACKET_M_H

