//
// Generated file, do not edit! Created by opp_msgtool 6.2 from messages/ICMPPacket.msg.
//

#ifndef __ICMPPACKET_M_H
#define __ICMPPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ICMPPacket;
/**
 * Class generated from <tt>messages/ICMPPacket.msg:1</tt> by opp_msgtool.
 * <pre>
 * message ICMPPacket
 * {
 *     string srcIP;
 *     string dstIP;
 *     int seqNum;
 *     bool isEchoRequest; // true = request, false = reply
 * }
 * </pre>
 */
class ICMPPacket : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string srcIP;
    omnetpp::opp_string dstIP;
    int seqNum = 0;
    bool isEchoRequest_ = false;

  private:
    void copy(const ICMPPacket& other);

  protected:
    bool operator==(const ICMPPacket&) = delete;

  public:
    ICMPPacket(const char *name=nullptr, short kind=0);
    ICMPPacket(const ICMPPacket& other);
    virtual ~ICMPPacket();
    ICMPPacket& operator=(const ICMPPacket& other);
    virtual ICMPPacket *dup() const override {return new ICMPPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSrcIP() const;
    virtual void setSrcIP(const char * srcIP);

    virtual const char * getDstIP() const;
    virtual void setDstIP(const char * dstIP);

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual bool isEchoRequest() const;
    virtual void setIsEchoRequest(bool isEchoRequest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ICMPPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ICMPPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ICMPPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<ICMPPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ICMPPACKET_M_H

